app/views/layouts/application.html.erb
____ Reviewed
- [] Bug Fix
* description
Sets up Bootstrap in project
closes #
=> Set up Bootstrap

.circleci/config.yml
____ Reviewed
- [] Bug Fix
* description
closes #
=> testing deploy

.circleci/config.yml
____ Reviewed
- [] Bug Fix
* description
closes #
=> caching gems

Gemfile, Gemfile.lock, app/controllers/welcome_controller.rb, app/views/welcome/index.html.erb, config/routes.rb
____ Reviewed
- [] Bug Fix
* description
closes #
=> Circleci deploy

.circleci/config.yml
____ Reviewed
- [] Bug Fix
* description
closes #
=> example PR

Gemfile.lock
____ Reviewed
- [] Bug Fix
* description
closes #
=> updated Gemfile.lock

app/facades/address_facade.rb, app/views/addresses/show.html.erb, spec/features/address_show_spec.rb
___x_ Wrote Tests
___x_ Implemented
__x__ Reviewed
- [] Bug Fix
* description
closes #14 
=> Address show 2

app/controllers/addresses_controller.rb, app/facades/address_facade.rb, app/models/address_search.rb, spec/features/user_can_find_an_address_spec.rb, spec/models/address_facade_spec.rb
__x__ Wrote Tests
____ Reviewed
- [] Bug Fix
* description
Returns user to find address page if address is invalid.
closes #13
=> Invalid address

app/facades/address_facade.rb, app/views/addresses/find.html.erb, app/views/addresses/show.html.erb
__X_ Implemented
____ Reviewed
* with the GOOGLE_MAPS_API_KEY only
- [] Bug Fix
Creates links on the address show page for Zillow, Google Maps, phone and email
closes #
=> Show links

app/facades/address_facade.rb, app/views/addresses/show.html.erb, spec/features/address_show_spec.rb, spec/models/address_facade_spec.rb
__x__ Wrote Tests
___x_ Implemented
___x_ Reviewed
- [] Bug Fix
* description
closes #35 
breaks out update method to interior updates and exterior updates and changes corresponding
tests. 
=> Address facade updates

app/assets/stylesheets/application.css, app/controllers/forms_controller.rb, app/facades/address_facade.rb, app/services/address_validation_service.rb, app/services/trelora_service.rb, app/views/addresses/show.html.erb, app/views/forms/new.html.erb, app/views/partials/_consultancy_form.html.erb, spec/features/address_show_spec.rb, spec/features/user_can_submit_home_forms_spec.rb, spec/services/address_validation_service_spec.rb
x Implemented
x Reviewed
- [] Bug Fix
* Update home collect form to have drop downs for month and year for cc expiration
closes #
=> Styling collect view

spec/models/address_facade_spec.rb
__x__ Wrote Tests
____ Reviewed
- x[] The code will run locally
* description
closes #
adds a test for the second opted in method. 
=> Adds model test for opted in.

app/controllers/forms_controller.rb, app/services/address_validation_service.rb, app/views/forms/new.html.erb, app/views/layouts/_flash.html.erb, app/views/partials/_consultancy_form.html.erb, spec/features/user_can_submit_home_forms_spec.rb
__x__ Wrote Tests
____ Reviewed
- [] Bug Fix
* description
* Implements a timer for the consultation with a final time being displayed upon submitting a form
* Converts form to read-only after clicking dismiss
closes #25 #29 #31
=> Consultation overlay 2

app/views/forms/new.html.erb
____ Reviewed
* description
Removes unnecessary code from changes made to the timer
closes #
=> Removed unnecessary timer code

app/views/forms/new.html.erb, app/views/layouts/application.html.erb
____ Reviewed
* description
Fixed modal to only open once by setting a cookie upon opening, then removing cookie after dismissing the finished modal.
closes #
=> Fixed modal

Gemfile.lock, app/controllers/addresses_controller.rb, app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/models/address.rb, app/views/addresses/find.html.erb, spec/features/address_show_spec.rb, spec/features/user_can_find_an_address_spec.rb, spec/features/user_can_submit_home_forms_spec.rb, spec/models/address_spec.rb
__x_ Wrote Tests
__x_ Implemented
__x_ Reviewed
- [] Bug Fix
* description
* Adds Address model, and select box for addresses on address find page
closes #
=> Address select

app/views/forms/new.html.erb
____ Reviewed
- [] Bug Fix
* description
closes #
=> Removed script tags

app/views/forms/new.html.erb
____ Reviewed
- [] Bug Fix
* description
closes #
=> Fix button

Gemfile, Gemfile.lock, Rakefile, app/controllers/application_controller.rb, app/facades/address_facade.rb, app/models/address_search.rb, app/views/addresses/show.html.erb, db/schema.rb, spec/factories/users.rb, spec/features/address_show_spec.rb, spec/models/address_facade_spec.rb, spec/rails_helper.rb, spec/services/address_validation_service_spec.rb
x Implemented
x Reviewed
* description
closes #
=> Rubocopping2.0

app/controllers/addresses_controller.rb, app/controllers/forms_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/address.rb, app/models/member_search.rb, app/services/trelora_service.rb, bin/webpack, bin/webpack-dev-server, bin/yarn
x Implemented
x Reviewed
* Rubocopping all the files
closes #
=> Rubocopping3.0

app/controllers/application_controller.rb, spec/features/unregistered_user_spec.rb, spec/features/user_can_find_an_address_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #
=> redirects a lost address to /find, adds an additional test
